### ISSUE TITLE
Root command completion

### ISSUE THREAD

**Issue by akemrir** [jxskiss/mcli#34]
I wanted to start discussion about this topic.

When someone would like to have very simple command without subcommands.
Let's say this:

```
package main

import (
	"fmt"

	"github.com/jxskiss/mcli"
)

type Config struct {
	field string
}

func cmdTestArguments(ctx mcli.ArgCompletionContext) []mcli.CompletionItem {
	return []mcli.CompletionItem{
		{Value: "cmd one", Description: "description one"},
		{Value: "cmd two", Description: "description two"},
	}
}

func cmdRoot(ctx *mcli.Context) {
	var args struct {
		Names bool   `cli:"-n, --names, Display certificate common names only."`
		Arg   string `cli:"arg, Dummy demo arg"`
		V     string `cli:"value"`
	}
	funcs := make(map[string]mcli.ArgCompletionFunc)
	funcs["arg"] = cmdTestArguments
	funcs["value"] = cmdTestArguments
	ctx.Parse(&args, mcli.DisableGlobalFlags(), mcli.WithArgCompFuncs(funcs))
	fmt.Println("Doing something")
}

func main() {
	app := &mcli.App{Description: `Very Simple App`}
	app.AddRoot(cmdRoot)

	app.Options.EnableFlagCompletionForAllCommands = true
	app.AddCompletion()
	app.AddHelp()
	app.Run()
}
```

What do you think about strategy for this?
I have started draft PR, it's still in progress.

**Comment by jxskiss** [comment]
You may try the code in branch `tmp_root_cmd_completion`, it should work as a base point.

But the root command support is not well designed and is buggy, e.g. for the program you provided, `program help` does not print help and exit, instead it runs the root command.

Originally, I thought comlicated needs should use sub-commands, root command was thoughout to be a simple default action when user does not provided any sub-command.

**Comment by akemrir** [comment]
Ok, I am writing to share some thoughts.

I have some mvp. But it needs some tweaks around flag suggestions on root command now.
I think checkLastArgForCompletion is way too complex. It needs refactor to reduce complexity.

When starting writing on root, I have planned procedure:
- suggest subcommands
- 0 subcommand suggestions, try to suggest completion for root function
- when not both above not doable because of condition, suggest subcommands/flags

When command with subcommands is not matched, this should handle more than one completion for root.
I still need to write more tests.

About help. Maybe in that case I would need to provide global -h flag, which would trigger ctx.PrintHelp() without adding a new command.
Then state it as prerequisite in order to use completion functions on this level.

What do you think about it?

**Comment by akemrir** [comment]
I am stuck on one thing. Flags are not get evaluated in some specific conditions.
When having root command, flags values does not change.

This minimal example can reproduce the problem:

```go
package main

import (
	"fmt"
	"os"

	"github.com/jxskiss/mcli"
)

type GlobalFlags struct {
	AcceptTOS bool `cli:"-a, --accept-tos, By setting this flag to true you indicate that you accept the current Let's Encrypt terms of service."`
}

var globalFlags GlobalFlags

func Execute() {
	app := mcli.App{}
	app.SetGlobalFlags(&globalFlags)
	app.AddRoot(Invoke)

	app.AddCompletion()
	app.Options.EnableFlagCompletionForAllCommands = true
	app.Run()
}

func main() {
	Execute()
}

func Invoke(_ *mcli.Context) {
	fmt.Println(os.Args)
	var args struct {
		Commands []string `cli:"command"`
		DryRun   bool     `cli:"-r, --dry-run, Dry run / don't execute"`
	}
	funcs := make(map[string]mcli.ArgCompletionFunc)
	funcs["command"] = CompleteComUnits
	mcli.Parse(&args, mcli.WithArgCompFuncs(funcs))

	fmt.Println(args)
	fmt.Println(globalFlags)
}

func CompleteComUnits(ctx mcli.ArgCompletionContext) []mcli.CompletionItem {
	return []mcli.CompletionItem{}
}
```

Then in command line:
![obraz](https://github.com/jxskiss/mcli/assets/240986/25ed5625-1ce6-49f7-8051-cea8ffdbea5b)

This problem is visible even without my changes from branch.

**Comment by akemrir** [comment]
Ok. Found it. It was caused by flag package.
When scanning arguments list it was failing when first encountered element was non flag.

Now I need to write down more tests.

**Comment by akemrir** [comment]
Ok. I saw merge, so I am closing issue.
