### ISSUE TITLE
Shell completion

### ISSUE THREAD

**Issue by akemrir** [jxskiss/mcli#8]
Hi, are there any plans to make shell completion?

**Comment by jxskiss** [comment]
Good point, shell completion is a nice feature to have, I will have a look at it.

**Comment by jxskiss** [comment]
@akemrir Hi, shell completion is implemented in pull request #11, you may try the latest release v0.8.0, any feedback is welcome.

**Comment by hc2h3o2** [comment]
@jxskiss Hi, I will surely give it a ride :) Just saw email about.
Any plans for fish shell also?

**Comment by akemrir** [comment]
Ok. Just checked. Completion works just fine :) It's a nice feature.
I can see command and it's flags.

Checked some combinations around that:

    Subcommands with different flags
    Main commands without groups
    Different completion command name

Everything worked.
Do you plan to expose descriptions also?

Like here?
![obraz](https://github.com/jxskiss/mcli/assets/240986/49a8b738-3d38-49f2-88e1-b72791d6c17b)

Cobra also allows to specify function to provide valid arguments for completion. To complete values for parameters.
![obraz](https://github.com/jxskiss/mcli/assets/240986/9a0a571d-b1a7-40c3-899a-2766404fa73a)

Nonethenless very nice feature :)
I like mcli for it's simplicity.

**Comment by akemrir** [comment]
Command without group is not suggested.

    // A sub-command can also be added without registering the group.
    mcli.Add("group3 sub1 subsub1", runGroup3Sub1Subsub1, "Blah blah Blah"

Maybe because of space?
![obraz](https://github.com/jxskiss/mcli/assets/240986/fe90c822-0701-42d1-a36d-24e48093f1eb)

![obraz](https://github.com/jxskiss/mcli/assets/240986/8f6681ea-eb28-4813-8a67-25846c5955d4)

After adding a group, it works like previous group.

**Comment by akemrir** [comment]
1. description - will check for bash and fish - I don't have accesss to powershell
2. no no, not argument validation. But suggestion of arguments for example
  --port TAB TAB -> 3000, 4000, 5000
  or with use of own function
  
![image](https://github.com/jxskiss/mcli/assets/240986/7d51cf0e-e937-4f30-8946-bbe92dbf37c2)

But I don't know where to put it properly.

**Comment by jxskiss** [comment]
1. nice ~
2. the most commonly used arg suggestion may be providing choice from a list (enum), for suggestion of this type, suggetion and validation are somehow related.
For more general arg suggestion, the use-case could be pretty complicated, I'm not sure how much effort does it need and whether it worth the complication.
If you want to give it a try, maybe a new struct tag `comp:"xxxx"`, then passing arg completion functions by adding a new ParseOpt is a good start point.

**Comment by akemrir** [comment]
Yep. Wanna try.
In most cases (at least for me) suggestions are local, based for example on configuration.
So in this case I would load config right before parsing and make completion function aware of that.

That's the plan. Will see how it will go.

**Comment by akemrir** [comment]
Could you show me output of:

```
issue  --mcli-generate-completion
```

**Comment by akemrir** [comment]
Ok. Found it why I don't see descriptions.
It's based on shell set in env not the one used in background.
In my case even when I launch terminal -e zsh I would have SHELL=/usr/bin/fish

I will analyse and maybe prepare PR for this.
Later for arguments completion.

**Comment by jxskiss** [comment]
@akemrir The way to check shell type is borrowed from other cli library (without much thinking), maybe there is better way to do this. Perhaps we can pass the shell type in command line, since we use seperate completion script for each shell type, we have full control on the command line arguments.

**Comment by akemrir** [comment]
That's actually good idea. And based on that type change separator contents text and description.

```
--mcli-generate-completion bash
--mcli-generate-completion zsh
```

Fish shell uses \t
Zsh uses : 
We need to check bash

**Comment by akemrir** [comment]
ok, I have mvp for unixes
![obraz](https://github.com/jxskiss/mcli/assets/240986/9a3a3ed4-c97d-4d5e-82c8-7c625c1114c1)

Now I need to work on tests.

Do you plan to suggest also help params?

**Comment by jxskiss** [comment]
Yes, I think help params should also be suggested.

**Comment by akemrir** [comment]
Ok, I've made second PR.

I wrote shell completion with descriptions.
It needs review. I made two comments on purpose.
Trying to figure out how to handle unsupported shells.

It should not happen, because we supply proper completion parameter upfront.
But if someone would change it, I think we should handle it somehow.

Maybe to throw error? (TODO in code)

**Comment by akemrir** [comment]
Do you plan any more changes? I will start in a free time with flag value suggestions.

**Comment by jxskiss** [comment]
@akemrir No. I have tagged a new version v0.8.3, you can start from the latest main branch.

**Comment by akemrir** [comment]
Thanks for info.

**Comment by akemrir** [comment]
Hi, I was doing research and checking out this parse options.
You were right. It's quite complicated to do. Till now I haven't got it working.

Beside of that, I checked how cobra is doing this.

mcli currently have suggestions for commands and flags.
On the other hand cobra is passing completion function as argument, doing it this way:
![obraz](https://github.com/jxskiss/mcli/assets/240986/1b968006-5a39-4554-965b-d40bbcbe4cac)

This is on command creation level.
Next when doing completion for current command it executes this function to get suggestions:
![obraz](https://github.com/jxskiss/mcli/assets/240986/7200c333-08fb-47cf-ae69-b2606ba9c50f)

Only when dash is present it suggests flags for command:
![obraz](https://github.com/jxskiss/mcli/assets/240986/4ea54e2e-0771-4bd7-91e2-a692f17e86a3)

Maybe we could do the same or similar?
![obraz](https://github.com/jxskiss/mcli/assets/240986/c806d50c-a67e-4d25-8b35-9d60f9365da9)

I know this is something opposite. Flag vs arguments completion.
I am not stopping approach for flags values suggestion.
What do you think about this idea?

**Comment by jxskiss** [comment]
I haven't understand the target use-case, could you state the user problem you are trying to solve in more details, better with real-world examples.

**Comment by akemrir** [comment]
Ok. Let's see.

We have three topics:
- flags completion
- help completion
- arguments completion

This is for third topic.

For example you would have this kind of configuration (taskfile.dev).

![obraz](https://github.com/jxskiss/mcli/assets/240986/7d8a27ce-0c2c-405f-86de-ea0968c72bc4)

And you would like to have many user predefined commands/tasks.
You would need to have help to show all of them, or suggest as valid arguments.

```
task <tab>
task hello
task hello <tab>
task hello world
```

hello and world are both tasks to execute

**Comment by jxskiss** [comment]
By "arguments completion", do you mean positional arguments? Do we need to suggest value for a flag which takes argument?

**Comment by akemrir** [comment]
Yes positional arguments. hello and world came from function outside of mcli lib.
Flags always start with dash `-`

So procedure would be like this:
- do I have subcommand to suggest?
- if there is no subcommands and no flags suggested execute command arguments function
- if we type dash - try to suggest flags
- if last already suggested is flag check if it has function and execute it to suggest value

When we have exact command we could always try to suggest or arguments or flags or flag values.
Because we could have dash condition.

To be more precise and complete, as in example mcli/examples/github-cli/main.go

Subcommand suggestion (done)
```
gh <tab>
gh browse
```

(command function) Function suggesting positional argument for command, e.g. pull request number:
```
gh browse <tab>
gh browse 217
```

(argument function) Function suggesting branches names for flags:
```
gh browse -b <tab>
gh browse -b PROJ-123
```

Our normal flag suggestion (done)
```
gh browse -<tab>
gh browse --settings
```

(argument function) at the end value for settings:
```
gh browse --settings <tab>
```

In general, I want to pass completion function for command to get positional arguments.
And second one, per flag to get flag value. To simplify it should receive only one value.

**Comment by jxskiss** [comment]
I see, powerful argument suggestion is very helpful to end user indeed.
It should be quite straightforward for flag value completion, but for positional arguments, it's a little complicated to decide which argument to suggest. Also boolean flag accepts flag value optionally, we may need to really parse the comamnd line to make a correct decision.

e.g.

```Go
type args struct {
	Approve bool   `cli:"-a"`
	Name    string `cli:"-n"`
	Branch  string `cli:"branch"`
	Message string `cli:"message"`
}
```

For this definition, these commands are all equal, which means `Approve=true, Name=Tom`.

- `program -a -b=Tom`
- `program -a=1 -b=Tom`
- `program -a=true -b Tom`

 Go ahead. I'm glad to give a hand if needed.

**Comment by jxskiss** [comment]
I added some comments in branch `tmp_arg_suggestion_draft`, you may check it to get some thoughts.

**Comment by akemrir** [comment]
I had similar ideas. https://github.com/akemrir/mcli/tree/PR-003
Now I need to read through over all of these changes.

**Comment by akemrir** [comment]
Hi, I have mvp. But I have question:
Do we want to allow more than one appearance of same flag? or this was a bug during completion?

On my current state mcli will not suggest already suggested flag.

I made also a change, which would require user to type hyphen to suggest flags.
We need also review this -a=1 situation. Suggestions right now don't make use of = character.

Right now I am on the stage of writing tests to cover various cases.

**Comment by akemrir** [comment]
ok, found answer for double appearance of flag

**Comment by akemrir** [comment]
I want to discuss directives.

Let's take a look on these examples:
[cobra/zsh_completions.go at main · spf13/cobra](https://github.com/spf13/cobra/blob/main/zsh_completions.go)
[cobra/bash_completions.go at main · spf13/cobra](https://github.com/spf13/cobra/blob/main/bash_completions.go)
[cobra/fish_completions.go at main · spf13/cobra](https://github.com/spf13/cobra/blob/main/fish_completions.go)

With current code we enforce developer to fill completion arguments with descriptions.
When description is empty string we leave only left side, option name.

When I take a look on these directives, they feel a bit obsolete.
```
    local shellCompDirectiveError=%[3]d
    local shellCompDirectiveNoSpace=%[4]d
    local shellCompDirectiveNoFileComp=%[5]d
    local shellCompDirectiveFilterFileExt=%[6]d
    local shellCompDirectiveFilterDirs=%[7]d
    local shellCompDirectiveKeepOrder=%[8]d
```

The plan is to provide completion by function at start.
But all of these extra options could be done inside of go code.
Only in cases when we would like to drop completion to shell in some special simple cases:
- only directories
- only files
- files filtered by extension.

These simple cases could be too complex also. Which app/utility to use to handle them? find, ls?
What to do if it would be missing? (windows, minimal docker image)

When someone would like to have extra logic changing the behavior, he needs to write some code nonetheless.

On the other hand, you suggested this:

	`comp:"nofile"`
	`comp:"enums=a,b,c,d;"`
	`comp:"fn=funcName"`
	`comp:"listExt=json,yaml,toml"`
	`comp:"listFiles"`  // and listDirs, listDirsAndFiles, etc.

So in fact they comply with internal functions?
Or we expect to drop handling to shell?

I see these enormous shell functions as over complication.
It should be simple, developer should be responsible for handling complex cases.

Your examples should be simple functions too, from mcli side.
To not expose them to performance degradation.

If someone wants to customize, do traversal, have faster execution etc., he should write own function.


By the way, I used double nested slices of strings in code, to be able to pass description.
mcli know which shell is used, hence knows which separator to use.

TODO: Fix bash, only which stoppped to work properly.

**Comment by jxskiss** [comment]
@akemrir Yes, I also think we should keep it simple on mcli side. By the draft code I given above, it is very incomplete and just providing some thoughts.
I will take a look at the PR, thank you for the contribution and deep thinking of this.

**Comment by akemrir** [comment]
Ok, please review,so I will address all remakrs at once. During update I will clean directives from code.

**Comment by akemrir** [comment]
Please take a look on bugfix. I had to update fish shell completion.

**Comment by jxskiss** [comment]
@akemrir Thank you very much for all the effort on this feature, I have merged the new PR.
I think this feature is almost finished, I am going to close this if I you also agree.

**Comment by akemrir** [comment]
I agree. Just tested with 0.9.1 and worked like charm :)
We could plan help suggestions but in separate issue, if needed.

Thank you very much for help with development.
